[project]
name = "admission-form"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
